### ISSUE TITLE
Docker support? 

### ISSUE THREAD

**Issue by alexander-gr** [heshu-by-lab/likelib-utonhack-2020#1]
Any plans about running the node from docker?

**Comment by magnusducatuslt** [comment]
я конечно не проффи, но кажись самому можно у докер положить и стартануть

**Comment by heshu-by-lab** [comment]
You can build and run node in docker. Example in .gitlab-ci.yml
Current docker image for build and testing you can see in image section from config file .gitlab-ci.yml
(heshuby/prepare_build:634fb3b872c5e57b04ed10090553c23a)

**Comment by heshu-by-lab** [comment]
For run node without build from source you can use next command `docker run -it -p 50051:50051 -p 50052:50052 -p 20203:20203 heshuby/utonhack:2020-07-10 ./node`
For check connection you need builded client `./client connection_test --host 127.0.0.1:50051` for http `./client connection_test --host 127.0.0.1:50052 --http`
Port 20203 need for nodes synchronization, and not using in single node case. You can disable this port.

This container builded from Dockerfile
```
FROM heshuby/prepare_build:634fb3b872c5e57b04ed10090553c23a

ENV INSTALL_DIR /opt/lkl
ENV SOURCE_DIR /opt/likelib
ENV BUILD_DIR ${SOURCE_DIR}/build
RUN mkdir ${SOURCE_DIR} && mkdir ${INSTALL_DIR}
WORKDIR ${SOURCE_DIR}
COPY likelib ${SOURCE_DIR}
COPY config.json ${INSTALL_DIR}
RUN cmake -DCMAKE_BUILD_TYPE=Release -S ${SOURCE_DIR} -B ${BUILD_DIR}
WORKDIR ${BUILD_DIR}
RUN make -j$(nproc)
RUN cp bin/* ${INSTALL_DIR}
WORKDIR ${INSTALL_DIR}
RUN rm -rf ${SOURCE_DIR}
```

**Comment by heshu-by-lab** [comment]
For work with network with transactions use command `docker run -it -p 2003:2003 -p 5051:5051 -p 5052:5052 heshuby/utonhack:2020-07-16 ./node`.
If you want only connect to network and don't want run node, you can use client `docker run -it heshuby/utonhack:2020-07-16 ./client node_info --host 86.57.193.146:50051` or `docker run -it heshuby/utonhack:2020-07-16 ./client node_info --http --host 86.57.193.146:50052`.
You can use `curl` for get JSON `curl http://86.57.193.146:50052/get_node_info --data ""` without docker.
Some transactions will automatically appear in this network, which we will generate throughout the entire hackathon.

**Comment by heshu-by-lab** [comment]
`heshuby/utonhack:2020-07-18-private` - in this image we can use only WS, node not connected to public network with some transaction
`heshuby/utonhack:2020-07-18-public` - in this image we can use only WS, node connected to public network with some transaction

**Comment by heshu-by-lab** [comment]
`heshuby/utonhack:2020-07-20-private` - only WS, problem with call method with N array parameters - Solved, base-account-keys copied to working directory

**Comment by heshu-by-lab** [comment]
`heshuby/utonhack:2020-07-21-private` - fixed difficulty of mining

**Comment by heshu-by-lab** [comment]
`heshuby/utonhack:2020-07-21-v2-private` - now the encoder is processing empty arrays

**Comment by heshu-by-lab** [comment]
`heshuby/utonhack:2020-07-22-private` - set difficulty of mining 10 transaction per 1 minute

**Comment by heshu-by-lab** [comment]
The hackathon is over. But if you have questions about likelib you can ask them!
